//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/_Project/Settings/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TodoBoard
{
    public partial class @UserInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UserInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""97e7cda3-42a9-459b-8164-4b1a022b999b"",
            ""actions"": [
                {
                    ""name"": ""ToggleAlwaysOnTop"",
                    ""type"": ""Button"",
                    ""id"": ""b541d593-3501-4a27-bc1a-ffa7bdf8e6cb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HideAllPanels"",
                    ""type"": ""Button"",
                    ""id"": ""87e7b7b7-c1e9-4993-a115-a75934822de7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8cc509c-0d4a-4a74-8915-e31f64a2d0d4"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAlwaysOnTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d91d9a3-be0d-4c1c-a249-e6070abfc26e"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HideAllPanels"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_ToggleAlwaysOnTop = m_UI.FindAction("ToggleAlwaysOnTop", throwIfNotFound: true);
            m_UI_HideAllPanels = m_UI.FindAction("HideAllPanels", throwIfNotFound: true);
        }

        ~@UserInput()
        {
            UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, UserInput.UI.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_ToggleAlwaysOnTop;
        private readonly InputAction m_UI_HideAllPanels;
        public struct UIActions
        {
            private @UserInput m_Wrapper;
            public UIActions(@UserInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleAlwaysOnTop => m_Wrapper.m_UI_ToggleAlwaysOnTop;
            public InputAction @HideAllPanels => m_Wrapper.m_UI_HideAllPanels;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @ToggleAlwaysOnTop.started += instance.OnToggleAlwaysOnTop;
                @ToggleAlwaysOnTop.performed += instance.OnToggleAlwaysOnTop;
                @ToggleAlwaysOnTop.canceled += instance.OnToggleAlwaysOnTop;
                @HideAllPanels.started += instance.OnHideAllPanels;
                @HideAllPanels.performed += instance.OnHideAllPanels;
                @HideAllPanels.canceled += instance.OnHideAllPanels;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @ToggleAlwaysOnTop.started -= instance.OnToggleAlwaysOnTop;
                @ToggleAlwaysOnTop.performed -= instance.OnToggleAlwaysOnTop;
                @ToggleAlwaysOnTop.canceled -= instance.OnToggleAlwaysOnTop;
                @HideAllPanels.started -= instance.OnHideAllPanels;
                @HideAllPanels.performed -= instance.OnHideAllPanels;
                @HideAllPanels.canceled -= instance.OnHideAllPanels;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        public interface IUIActions
        {
            void OnToggleAlwaysOnTop(InputAction.CallbackContext context);
            void OnHideAllPanels(InputAction.CallbackContext context);
        }
    }
}
